services:
  web-laravel-monetary-account:
    build: 
      context: web-laravel-monetary-account
      dockerfile: ../Dockerfile
      target: base
    container_name: web-laravel-monetary-account
    image: web-laravel-monetary-account
    env_file:
      - .env
  web-laravel-monetary-authentication:
    build: 
      context: web-laravel-monetary-authentication
      dockerfile: ../Dockerfile
      target: base
    container_name: web-laravel-monetary-authentication
    image: web-laravel-monetary-authentication
    env_file:
      - .env
  web-laravel-monetary-budget:
    build: 
      context: web-laravel-monetary-budget
      dockerfile: ../Dockerfile
      target: base
    container_name: web-laravel-monetary-budget
    image: web-laravel-monetary-budget
    env_file:
      - .env
  web-laravel-monetary-category:
    build: 
      context: web-laravel-monetary-category
      dockerfile: ../Dockerfile
      target: base
    container_name: web-laravel-monetary-category
    image: web-laravel-monetary-category
    env_file:
      - .env
  web-laravel-monetary-debt:
    build: 
      context: web-laravel-monetary-debt
      dockerfile: ../Dockerfile
      target: base
    container_name: web-laravel-monetary-debt
    image: web-laravel-monetary-debt
    env_file:
      - .env
  web-laravel-monetary-recurrence:
    build: 
      context: web-laravel-monetary-recurrence
      dockerfile: ../Dockerfile
      target: base
    container_name: web-laravel-monetary-recurrence
    image: web-laravel-monetary-recurrence
    env_file:
      - .env
  web-laravel-monetary-transaction:
    build: 
      context: web-laravel-monetary-transaction
      dockerfile: ../Dockerfile
      target: base
    container_name: web-laravel-monetary-transaction
    image: web-laravel-monetary-transaction
    env_file:
      - .env
