services:
  web-laravel-monetary-account:
    build: ./web-laravel-monetary-account
    container_name: web-laravel-monetary-account
    image: web-laravel-monetary-account
    ports:
      - 8001:80
    env_file:
      - ./web-laravel-monetary-account/.env
  web-laravel-monetary-authentication:
    build: ./web-laravel-monetary-authentication
    container_name: web-laravel-monetary-authentication
    image: web-laravel-monetary-authentication
    ports:
      - 8002:80
    env_file:
      - ./web-laravel-monetary-authentication/.env
  web-laravel-monetary-budget:
    build: ./web-laravel-monetary-budget
    container_name: web-laravel-monetary-budget
    image: web-laravel-monetary-budget
    ports:
      - 8003:80
    env_file:
      - ./web-laravel-monetary-budget/.env
  web-laravel-monetary-category:
    build: ./web-laravel-monetary-category
    container_name: web-laravel-monetary-category
    image: web-laravel-monetary-category
    ports:
      - 8004:80
    env_file:
      - ./web-laravel-monetary-category/.env
  web-laravel-monetary-debt:
    build: ./web-laravel-monetary-debt
    container_name: web-laravel-monetary-debt
    image: web-laravel-monetary-debt
    ports:
      - 8005:80
    env_file:
      - ./web-laravel-monetary-debt/.env
  web-laravel-monetary-recurrence:
    build: ./web-laravel-monetary-recurrence
    container_name: web-laravel-monetary-recurrence
    image: web-laravel-monetary-recurrence
    ports:
      - 8006:80
    env_file:
      - ./web-laravel-monetary-recurrence/.env
  web-laravel-monetary-transaction:
    build: ./web-laravel-monetary-transaction
    container_name: web-laravel-monetary-transaction
    image: web-laravel-monetary-transaction
    ports:
      - 8007:80
    env_file:
      - ./web-laravel-monetary-transaction/.env
