name: Deploy Recurrence Microservice

on:
  push:
    branches:
      - deployment
    paths:
      - web-laravel-monetary-recurrence/**
      - .github/workflows/web-laravel-monetary-recurrence-deploy.yml
      - docker compose.yml
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    env:
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE: postgres
      JWT_SECRET: bp1YZ1lfj5FceqNeccHoKiIkZUX5rLa1msSWy9zzjpCdiDGRdrvM4WN6IUYqhkSL
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        env:
          runner: self-hosted
        with:
          php-version: 8.2
          extensions: mbstring, dom, fileinfo, pgsql
          coverage: xdebug

      - name: Install Composer dependencies
        run: |
          composer install --working-dir=web-laravel-monetary-account --no-progress --prefer-dist --optimize-autoloader
          composer install --working-dir=web-laravel-monetary-authentication --no-progress --prefer-dist --optimize-autoloader
          composer install --working-dir=web-laravel-monetary-budget --no-progress --prefer-dist --optimize-autoloader
          composer install --working-dir=web-laravel-monetary-category --no-progress --prefer-dist --optimize-autoloader
          composer install --working-dir=web-laravel-monetary-debt --no-progress --prefer-dist --optimize-autoloader
          composer install --working-dir=web-laravel-monetary-recurrence --no-progress --prefer-dist --optimize-autoloader
          composer install --working-dir=web-laravel-monetary-transaction --no-progress --prefer-dist --optimize-autoloader

      - name: Run database migrations
        run: |
          php web-laravel-monetary-authentication/artisan migrate:fresh --seed --force
          php web-laravel-monetary-account/artisan migrate --seed --force
          php web-laravel-monetary-category/artisan migrate --seed --force
          php web-laravel-monetary-transaction/artisan migrate --seed --force
          php web-laravel-monetary-recurrence/artisan migrate --seed --force
          php web-laravel-monetary-debt/artisan migrate --seed --force
          php web-laravel-monetary-budget/artisan migrate --seed --force

      - name: Run PHP Unit Tests
        run: |
          cd web-laravel-monetary-recurrence
          vendor/bin/phpunit

      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            [ ! -d web-monetary ] && git clone https://github.com/zS1L3NT/web-monetary
            cd web-monetary
            git pull origin deployment
            APP_KEY="${{ secrets.APP_KEY }}" \
            DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
            DB_HOST="${{ secrets.DB_HOST }}" \
            DB_PORT="${{ secrets.DB_PORT }}" \
            DB_DATABASE="${{ secrets.DB_DATABASE }}" \
            DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            docker compose up -d --build web-laravel-monetary-recurrence web-laravel-monetary-recurrence-scheduler