name: Deploy Account Microservice

on:
  push:
    branches:
      - main
    paths:
      - 'web-laravel-monetary-account/**'

jobs:
  push_to_docker_hub:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Extract metadata (tags, labels) for Docker
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: zs1l3nt/web-laravel-monetary-account

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          context: .
          file: ./web-laravel-monetary-account/Dockerfile
          push: true
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}

  update_linode:
    name: Update Linode
    needs: push_to_docker_hub
    runs-on: ubuntu-latest
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_ACCOUNT_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          script: |
            docker stop web-laravel-monetary-account
            docker rm web-laravel-monetary-account
            docker rmi zs1l3nt/web-laravel-monetary-account:latest
            docker pull zs1l3nt/web-laravel-monetary-account:latest
            docker run -d --name web-laravel-monetary-account -p 80:80 zs1l3nt/web-laravel-monetary-account:latest