name: Test, Build and Deploy Budget Microservice

on:
  push:
    branches:
      - main
    paths:
      - web-laravel-monetary-budget/**
      - .github/workflows/web-laravel-monetary-budget.yml
      - docker-compose.yml
      - Dockerfile

jobs:
  test:
    runs-on: ubuntu-latest
    env:
      DB_CONNECTION: pgsql
      DB_HOST: localhost
      DB_PASSWORD: postgres
      DB_USERNAME: postgres
      DB_DATABASE: postgres
      JWT_SECRET: bp1YZ1lfj5FceqNeccHoKiIkZUX5rLa1msSWy9zzjpCdiDGRdrvM4WN6IUYqhkSL
    services:
      postgres:
        image: postgres:14
        env:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: postgres
          POSTGRES_DB: postgres
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: 8.2
          extensions: mbstring, dom, fileinfo, pgsql
          coverage: xdebug

      - name: Install composer dependencies
        run: head -n -1 install.sh | bash

      - name: Run database migrations
        run: ./migrate.sh

      - name: Create app key
        run: echo "APP_KEY=$(php web-laravel-monetary-budget/artisan key:generate --show)" >> $GITHUB_ENV

      - name: Run authentication microservice
        run: nohup php web-laravel-monetary-authentication/artisan serve &

      - name: Run tests with PHP Unit
        run: cd web-laravel-monetary-budget && vendor/bin/phpunit tests

  build:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and Push to Docker Hub
        uses: docker/build-push-action@v2
        with:
          file: Dockerfile
          context: web-laravel-monetary-budget
          push: true
          tags: zs1l3nt/web-laravel-monetary-budget:latest

  deploy:
    runs-on: ubuntu-latest
    environment: production
    needs: build
    steps:
      - name: Redeploy the docker containers on the server
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            docker stop web-laravel-monetary-budget
            docker rm web-laravel-monetary-budget
            docker rmi zs1l3nt/web-laravel-monetary-budget:latest
            docker pull zs1l3nt/web-laravel-monetary-budget:latest
            docker run -d \
              -p 8003:80 \
              -e APP_KEY="${{ secrets.APP_KEY }}" \
              -e DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
              -e DB_HOST="${{ secrets.DB_HOST }}" \
              -e DB_PORT="${{ secrets.DB_PORT }}" \
              -e DB_DATABASE="${{ secrets.DB_DATABASE }}" \
              -e DB_USERNAME="${{ secrets.DB_USERNAME }}" \
              -e DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
              -e JWT_SECRET="${{ secrets.JWT_SECRET }}" \
              --name web-laravel-monetary-budget \
              --restart unless-stopped \
              zs1l3nt/web-laravel-monetary-budget:latest