name: Deploy Account Microservice

on:
  push:
    branches:
      - main
      - deployment
    paths:
      - 'web-laravel-monetary-account/**'
      - '.github/workflows/web-laravel-monetary-account-deploy.yml'

jobs:
  push_to_docker_hub:
    name: Push Docker Image to Docker Hub
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repository
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        run: docker login -u ${{ secrets.DOCKER_USERNAME }} -p ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker Image
        run: docker build -t zs1l3nt/web-laravel-monetary-account web-laravel-monetary-account
      
      - name: Push Docker Image to Docker Hub
        run: docker push zs1l3nt/web-laravel-monetary-account

  update_linode:
    name: Update Linode
    needs: push_to_docker_hub
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run new Docker Container
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_ACCOUNT_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          script:  |
            APP_KEY="${{ secrets.APP_KEY }}" ; \
            DB_CONNECTION="${{ secrets.DB_CONNECTION }}" ; \
            DB_HOST="${{ secrets.DB_HOST }}" ; \
            DB_PORT="${{ secrets.DB_PORT }}" ; \
            DB_DATABASE="${{ secrets.DB_DATABASE }}" ; \
            DB_USERNAME="${{ secrets.DB_USERNAME }}" ; \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" ; \
            JWT_SECRET="${{ secrets.JWT_SECRET }}" ; \
            ./start