name: Deploy Account Microservice

on:
  push:
    branches:
      - main
      - deployment
    paths:
      - web-laravel-monetary-account/**
      - .github/workflows/web-laravel-monetary-account-deploy.yml
      - docker-compose.yml
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.LINODE_ACCOUNT_HOST }}
          username: ${{ secrets.LINODE_USERNAME }}
          password: ${{ secrets.LINODE_PASSWORD }}
          script: |
            cd /home/web-monetary
            echo APP_KEY="${{ secrets.APP_KEY }}" > .env
            echo DB_CONNECTION="${{ secrets.DB_CONNECTION }}" >> .env
            echo DB_HOST="${{ secrets.DB_HOST }}" >> .env
            echo DB_PORT="${{ secrets.DB_PORT }}" >> .env
            echo DB_DATABASE="${{ secrets.DB_DATABASE }}" >> .env
            echo DB_USERNAME="${{ secrets.DB_USERNAME }}" >> .env
            echo DB_PASSWORD="${{ secrets.DB_PASSWORD }}" >> .env
            echo JWT_SECRET="${{ secrets.JWT_SECRET }}" >> .env
            git pull origin main
            docker-compose up -d --build