name: Deploy Recurrence Microservice

on:
  push:
    branches:
      - deployment
    paths:
      - web-laravel-monetary-recurrence/**
      - .github/workflows/web-laravel-monetary-recurrence-deploy.yml
      - docker compose.yml
      - Dockerfile

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Run update command
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          script: |
            [ ! -d web-monetary ] && git clone https://github.com/zS1L3NT/web-monetary
            cd web-monetary
            git pull origin deployment
            APP_KEY="${{ secrets.APP_KEY }}" \
            DB_CONNECTION="${{ secrets.DB_CONNECTION }}" \
            DB_HOST="${{ secrets.DB_HOST }}" \
            DB_PORT="${{ secrets.DB_PORT }}" \
            DB_DATABASE="${{ secrets.DB_DATABASE }}" \
            DB_USERNAME="${{ secrets.DB_USERNAME }}" \
            DB_PASSWORD="${{ secrets.DB_PASSWORD }}" \
            JWT_SECRET="${{ secrets.JWT_SECRET }}" \
            docker compose up -d --build web-laravel-monetary-recurrence web-laravel-monetary-recurrence-scheduler